### ISSUE TITLE
The newest version always returns the same value for the gasresistance 

### ISSUE THREAD

**Issue by caemor** [marcelbuesing/bme680#3]
Hello,
sorry for bugging you once more :-D

But the Gasresistance stays the same for the newest github commit even over very long times ( i have it running for 3 hours now - and a second shorter test with a different bme which returned a different constant value). 

I must happened between the i2c-address enum commit and the newest commit.
Or is this an error in my program settings and it works on your end? (although they should be the same as the examples :-D )

Greetings and thanks for your amazing work,
Chris

**Comment by marcelbuesing** [comment]
Thanks for reporting this. I actually had the feeling that the gas resistance looked a little bit too constant. I will try to figure out where the bug is.

Ok git bisecting it, seems the bug appeared in `44fc891b3e6e744971fccb6b7b038cfe08271e49`.

**Comment by marcelbuesing** [comment]
Pretty confident I found it. I missed setting a flag in the SettingsBuilder. Which lead to never actually setting the gas config via I2C. Please let me know if the fix works for you, then I'll make a `0.3.1` release

**Comment by caemor** [comment]
I only had a few minutes before leaving this morning, so i wasn't able to test it better.
But a short `cargo update`, followed by building and running it, didn't change it for me.

I need to take a look at the cargo.lock if it really changed to your new patch when i come back this evening.

**Comment by caemor** [comment]
that one fixed it :+1: 
i was just testing through all the commits right now :-D

**Comment by marcelbuesing** [comment]
Thanks for testing it! Just released 0.3.1
